vo=gpu-next
gpu-api=vulkan          # 若 vulkan 有问题可改为 opengl
scale=ewa_lanczossharp
hwdec=auto-safe

# 默认不加载着色器，由 auto-profile 按分辨率选择
glsl-shaders=""
load-auto-profiles=yes

[4k]
profile-cond=height >= 2160
profile-restore=copy
glsl-shaders=""

[fhd]
profile-cond=height > 720 and height <= 1080
profile-restore=copy
glsl-shaders="/usr/share/mpv-shim-default-shaders/shaders/FSRCNNX_x2_8-0-4-1.glsl"

[sd]
profile-cond=height <= 720
profile-restore=copy
glsl-shaders="/usr/share/mpv-shim-default-shaders/shaders/FSRCNNX_x2_8-0-4-1.glsl:/usr/share/mpv-shim-default-shaders/shaders/Anime4K_Restore_CNN_M.glsl:/usr/share/mpv-shim-default-shaders/shaders/CAS-scaled.glsl"

ytdl=yes
script-opts=ytdl_hook-ytdl_path=yt-dlp
ytdl-raw-options=cookies=/home/zmq/.cache/yt-dlp/cookies.txt,no-playlist=,socket-timeout=5

# 减少流分析时间
demuxer-lavf-analyzeduration=2
